sudo: false
addons:
  apt:
    packages:
      - rake
      - bison
      - git
      - gperf
language: c
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=1.2.0
  - MRUBY_VERSION=master
script:
  - rake clean
  - rake test